version: '3.3'
services:
  jenkins-docker:
    image: 'docker:dind'
    privileged: true  
    networks: 
      jenkins:
        aliases: 
          - docker
    environment: 
      - DOCKER_TLS_CERTDIR=/certs
    volumes:
      - "jenkins_data:/var/jenkins_home"
      - "jenkins-docker-certs:/certs/client"
      - "$HOME:/home" 
  
  jenkins:
    image: 'jenkinsci/blueocean'
    ports:
      - '80:8080'
      - '443:8443'
      - '50000:50000'
    networks: 
      - jenkins
    environment: 
      - DOCKER_HOST=tcp://docker:2376
      - DOCKER_CERT_PATH=/certs/client
      - DOCKER_TLS_VERIFY=1
    volumes:
      - "jenkins_data:/var/jenkins_home"
      - "jenkins-docker-certs:/certs/client:ro"
      - "$HOME:/home" 
   
      
networks: 
  jenkins:

volumes:
  jenkins_data:
  jenkins-docker-certs: